import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

const directories: string[] = [];
afterEach(() => {
  for (const dir of directories.splice(0)) rmSync(dir, { recursive: true, force: true });
});

// A fake docker that records each call with the settings Compose would see,
// and answers only what the upgrade asks.
const fakeDocker = `#!/bin/sh
printf '%s | image=%s file=%s pwd=%s\\n' "$*" "\${PASSDOWN_IMAGE-unset}" "\${COMPOSE_FILE-unset}" "$PWD" >> "$DOCKER_LOG"
case "$*" in
  *' ps -q web') [ "$WEB_RUNNING" = 1 ] && printf '%s\\n' web-container ;;
  *' ps -q proxy') printf '%s\\n' proxy-container ;;
  'inspect --format {{.State.Running}} web-container') printf '%s\\n' true ;;
  'inspect --format {{.Image}} web-container') printf '%s\\n' sha256:previous-web ;;
  'inspect --format {{.Image}} proxy-container') printf '%s\\n' sha256:previous-proxy ;;
  *' run --rm -T migrate') exit "\${MIGRATE_STATUS:-0}" ;;
  *' run --rm -T ops version') printf '%s\\n' 'passdown 0.0.2 (revision abc)' ;;
  *' run --rm -T ops status') printf '%s\\n' 'Database schema is current (31 migrations applied).' 'Setup: complete' ;;
  *' up -d --no-deps --wait web proxy') exit "\${UP_STATUS:-0}" ;;
  'pull '*) exit "\${PULL_STATUS:-0}" ;;
esac
exit 0
`;

function installation(compose = 'compose.yaml:compose.build.yaml', image?: string) {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), 'passdown-upgrade-')));
  directories.push(dir);
  copyFileSync(resolve('deploy/upgrade.sh'), join(dir, 'upgrade.sh'));
  writeFileSync(
    join(dir, 'backup.sh'),
    `#!/bin/sh\nprintf '%s\\n' "backup $*" >> "$DOCKER_LOG"\nexit "\${BACKUP_STATUS:-0}"\n`,
  );
  const settings = [
    '# Generated by init.sh.',
    'COMPOSE_PROJECT_NAME=passdown-test',
    `COMPOSE_FILE=${compose}`,
    'GUIDE_DB_OWNER_PASSWORD=owner-secret',
    ...(image ? [`PASSDOWN_IMAGE=${image}`] : []),
  ];
  writeFileSync(join(dir, '.env'), settings.join('\n') + '\n', { mode: 0o600 });
  const bin = join(dir, 'bin');
  mkdirSync(bin);
  writeFileSync(join(bin, 'docker'), fakeDocker);
  chmodSync(join(bin, 'docker'), 0o700);
  return dir;
}
function upgrade(dir: string, args: string[], env: Record<string, string> = {}) {
  // Run from elsewhere: operators do not always start in the installation directory.
  const result = spawnSync('sh', [join(dir, 'upgrade.sh'), ...args], {
    cwd: tmpdir(),
    // A minimal environment, so nothing from this shell reaches the script.
    env: {
      PATH: `${join(dir, 'bin')}:${process.env.PATH}`,
      DOCKER_LOG: join(dir, 'docker.log'),
      WEB_RUNNING: '1',
      NODE_ENV: 'test',
      ...env,
    },
    encoding: 'utf8',
  });
  let calls: string[] = [];
  try {
    calls = readFileSync(join(dir, 'docker.log'), 'utf8').trim().split('\n');
  } catch {
    // No docker call was made.
  }
  return { ...result, calls };
}
const called = (calls: string[], fragment: string) =>
  calls.findIndex((call) => call.includes(fragment));

describe('upgrading a source-built installation', () => {
  it('backs up, keeps the previous images, migrates with the new build, then replaces web', () => {
    const dir = installation();
    const result = upgrade(dir, ['--build']);
    expect(result.status, result.stderr).toBe(0);
    const order = [
      'backup --env-file',
      'tag sha256:previous-web passdown:previous',
      'tag sha256:previous-proxy passdown-caddy:previous',
      ' build web proxy',
      ' run --rm -T migrate',
      ' up -d --no-deps --wait web proxy',
    ].map((fragment) => called(result.calls, fragment));
    expect(
      order.every((index) => index >= 0),
      JSON.stringify(result.calls),
    ).toBe(true);
    expect([...order].sort((a, b) => a - b)).toEqual(order);
    expect(result.stdout).toContain('passdown 0.0.2');
    // Settings name their Compose files relatively; Compose resolves them
    // against the working directory, so every command runs from the installation.
    for (const call of result.calls.filter((line) => line.startsWith('compose')))
      expect(call.endsWith(`pwd=${dir}`), call).toBe(true);
    const log = readFileSync(join(dir, 'upgrade.log'), 'utf8');
    expect(log).toContain('sha256:previous-web');
    expect(log).toContain('replaced web');
    expect(statSync(join(dir, 'upgrade.log')).mode & 0o777).toBe(0o600);
  });

  it('leaves the running site alone and points the build tags back when migrations fail', () => {
    const dir = installation();
    const result = upgrade(dir, ['--build'], { MIGRATE_STATUS: '1' });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain('still running the previous version');
    expect(called(result.calls, ' up -d')).toBe(-1);
    expect(called(result.calls, 'tag sha256:previous-web passdown:local')).toBeGreaterThan(
      called(result.calls, ' run --rm -T migrate'),
    );
    expect(called(result.calls, 'tag sha256:previous-proxy passdown-caddy:local')).toBeGreaterThan(
      -1,
    );
    expect(readFileSync(join(dir, 'upgrade.log'), 'utf8')).toContain('migrations failed');
  });

  it('stops before changing anything when the backup fails', () => {
    const dir = installation();
    const result = upgrade(dir, ['--build'], { BACKUP_STATUS: '1' });
    expect(result.status).toBe(1);
    for (const fragment of [' build ', ' run --rm -T migrate', ' up -d', 'tag '])
      expect(called(result.calls, fragment), fragment).toBe(-1);
  });

  it('refuses when the installation is not running, so a first start stays explicit', () => {
    const dir = installation();
    const result = upgrade(dir, ['--build'], { WEB_RUNNING: '0' });
    expect(result.status).toBe(4);
    expect(result.stderr).toContain('docker compose up -d');
    expect(called(result.calls, 'backup')).toBe(-1);
  });

  it('refuses --build for an installation that uses published images', () => {
    const dir = installation('compose.yaml');
    const result = upgrade(dir, ['--build']);
    expect(result.status).toBe(4);
    expect(result.calls).toEqual([]);
  });

  it('keeps Compose settings from the shell out of every command', () => {
    const dir = installation();
    const result = upgrade(dir, ['--build'], {
      COMPOSE_FILE: '/elsewhere/compose.yaml',
      PASSDOWN_IMAGE: 'attacker/image:latest',
    });
    expect(result.status, result.stderr).toBe(0);
    for (const call of result.calls.filter((line) => line.startsWith('compose')))
      expect(call).toContain('| image=unset file=unset pwd=');
  });
});

describe('upgrading to a published image', () => {
  const next = 'ghcr.io/nanwer/passdown:0.1.0-alpha.2';
  it('migrates with the new image and records it in the settings only after success', () => {
    const dir = installation('compose.yaml', 'ghcr.io/nanwer/passdown:0.1.0-alpha.1');
    const result = upgrade(dir, ['--image', next]);
    expect(result.status, result.stderr).toBe(0);
    expect(called(result.calls, `pull ${next}`)).toBeGreaterThan(called(result.calls, 'backup'));
    const migrate = result.calls[called(result.calls, ' run --rm -T migrate')]!;
    expect(migrate).toContain(`image=${next}`);
    const settings = readFileSync(join(dir, '.env'), 'utf8');
    expect(settings).toContain(`PASSDOWN_IMAGE=${next}\n`);
    expect(settings).not.toContain('0.1.0-alpha.1');
    expect(settings).toContain('GUIDE_DB_OWNER_PASSWORD=owner-secret');
    expect(statSync(join(dir, '.env')).mode & 0o777).toBe(0o600);
  });

  it('leaves the settings unchanged when migrations fail', () => {
    const dir = installation('compose.yaml', 'ghcr.io/nanwer/passdown:0.1.0-alpha.1');
    const before = readFileSync(join(dir, '.env'), 'utf8');
    const result = upgrade(dir, ['--image', next], { MIGRATE_STATUS: '1' });
    expect(result.status).toBe(1);
    expect(readFileSync(join(dir, '.env'), 'utf8')).toBe(before);
    expect(called(result.calls, ' up -d')).toBe(-1);
  });

  it('refuses an image reference that is not a plain registry reference', () => {
    const dir = installation('compose.yaml');
    for (const bad of ['', 'image with space', 'repo:tag;rm -rf /', '-rf'])
      expect(upgrade(dir, ['--image', bad]).status, bad).toBe(2);
  });
});
