// Generated by scripts/migration-manifest.mjs. Do not edit.
// Regenerate with: pnpm migrations:manifest
export const migrationManifest: { name: string; checksum: string }[] = [
  { name: '001_application.sql', checksum: 'b4c7de6aaa6726f95c577a8a265aa3eca7656a4818cb57a574ad39157206614a' },
  { name: '002_scope_binding.sql', checksum: '816438d1a60620c164c0eedb6c89084f84152ee95b4fd62e3e06bc17b711bb45' },
  { name: '003_restricted_states.sql', checksum: '5e39892cae7fb822d7f4b52afe05151ac8ba8c64a3c6255baf973db5eec37116' },
  { name: '004_event_scope_integrity.sql', checksum: 'e06a144b579df72cc6faaa7d236482053e80685e8a031005a0547364fb2a694c' },
  { name: '005_explicit_actor_context.sql', checksum: '0c80a2a012de9d9be756bf9e5f1769ce2a2de198e78a8298cbef255bf87a6ec8' },
  { name: '006_release_attribution.sql', checksum: '717cb822da03e7a980c6524651df5e2ff8a6af8d39f6c1dcef13a7c94b62be38' },
  { name: '007_structured_authoring.sql', checksum: '8f3aee169691d2a24091b2fa0df8004637df9f5c28d5ae7fd7f00227143081cc' },
  { name: '008_category_codes_and_counts.sql', checksum: '62e7802ed87de3844539f6ba0263c01f0bbcdaa24f747cb70147b2e460a4a351' },
  { name: '009_category_deactivation_blockers.sql', checksum: '819ce65bfe56882c584b2940e06e983180fd45f6ad881a67e08448f3065ac78d' },
  { name: '010_catalog_usage_counts.sql', checksum: '85aac3a388afff12534fe2088be2807f14e2e39db8acb74120549b29b0f27429' },
  { name: '011_media_assets.sql', checksum: 'b98d8cd38f1339d2bc4b0685ee8a28ba0d440313e7a88e198b5889bb5260a971' },
  { name: '012_guide_families.sql', checksum: '716ceb773471e817ceb5a6bbf4294b900ebe722bdce1f3d5f6255bd1911d8bd4' },
];
